services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: database
    ports:
      - "8000:8000"
    command: 
      - start
      - --log=trace
      - --user=root
      - --pass=root
      - --allow-guests
    restart: always
  # app:
  #   # image: poivre-axum:latest
  #   image: poivre/poivre-axum
  #   build: ./poivre-axum
  #   container_name: server
  #   ports:
  #     - 3000:3000
  #   command:
  #     - /bin/server
  #   depends_on: [surrealdb]
